### ISSUE TITLE
Disabling dock in switcher 

### ISSUE THREAD

**Issue by narcyzzo** [nahtedetihw/FloatingDockXVI#4]
Can u add this feature?

**Comment by nahtedetihw** [comment]
feature was added in latest version

**Comment by WestinYung** [comment]
![7C3C113D-FAF6-4527-8783-1CAFBC03BCFC](https://github.com/nahtedetihw/FloatingDockXVI/assets/11864525/a33d7028-50fd-4679-a867-ab977e5fb42a)
 Dock still consist on AppSwitcher in 1.5 while 'Disable dock in Apps' is enabled.🤔
