### ISSUE TITLE
Showing in apps when showing in apps is disabled

### ISSUE THREAD

**Issue by anShigenta** [nahtedetihw/FloatingDockXVI#9]
I've got a problem while using this tweak... So. First - it shows dock if i switch apps from mulitask panel(switcher). Second - it shows dock if i change landscape/portrait(rotate my phone). Third - it shows if im closing notification panel(and other things from bottom of the screen).

Please fix

**Comment by nahtedetihw** [comment]
Fixed in version 1.9, just uploaded to Havoc
